// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

const databaseUrl = env('DATABASE_URL') || 'postgresql://postgres:@localhost:5432/mynestdb?schema=public';

if (!databaseUrl) {
  throw new Error(
    'DATABASE_URL environment variable is not set. Please set it in your .env file.\n' +
      'Example: DATABASE_URL="postgresql://user:password@localhost:5432/database_name?schema=public"',
  );
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
});